### ISSUE TITLE
Consider updating External Links and Resources

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#493] opened 2020-04-29 14:24 UTC
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Example:
- https://orgbook-test.pathfinder.gov.bc.ca/en/connect#feedback

![image](https://user-images.githubusercontent.com/10504350/80605270-b11add80-89e7-11ea-8b79-74157f52d019.png)

Observed:
- The **External Links and Resources** links on the contact page direct the user to stale resources.
  -  The Verifiable Organizations Network links to the [VON GitHub Repository](https://github.com/bcgov/von), rather than a more suitable page such as the [vonx.io](https://vonx.io/) site.  The bigger issue here is most content is dated, and the latest updates (https://vonx.io/safeentry/) is not readily accessible from any of the site's main pages.
  - The **Fork us on GitHub** links to [bcgov/TheOrgBook](https://github.com/bcgov/TheOrgBook) rather than [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr), which will eventually be transferred to `hyperledger/aries-vcr`

Expected:
- The **External Links and Resources** link to up-to-date resources.

**Comment by ianco** [comment] 2020-05-04 18:46
re-assigning to @swcurran

**Comment by swcurran** [comment] 2020-05-05 20:58
The VON Link should be to either vonx.io (my preference) or a github link for the `verifiable-organization-network` topic (https://github.com/topics/verifiable-organizations-network).

Note that the safeentry page on vonx.io is not intended to be linked to any page on vonx.io at this time, so that's a feature not a bug.  To be determined is what is to be done with both vonx.io and the Safe Entry prototype.  Those are for @jljordan42 to decide.

The fork on github should go aries-vcr.

**Closed** 2020-09-08 15:58 UTC
