### ISSUE TITLE
Add filters to '/schema' API endpoint

### ISSUE THREAD

**Issue by esune** [bcgov/aries-vcr#386] opened 2019-01-03 18:48 UTC
The call to the `/schema` API endpoint currently returns a list containing all the versions of the schemas that have been published to the ledger, regardless of whether they are still active or not.

It would be useful to have the possibility to only request a list of the latest versions of each schema, and in particular of each schema that is still active (where active means that it appears to be active in ToB).

Question: is there any other API call in ToB that would benefit from the same filtering?

**Comment by swcurran** [comment] 2020-03-24 17:17
@nrempel - is this addressed by API v3?  Can we close this?

**Comment by esune** [comment] 2020-12-16 17:44
Quick check by using `curl -X GET "https://orgbook.gov.bc.ca/api/v3/schema" -H  "accept: application/json"`: it appears that currently only one version of each schema is being returned, however the sam can be said for the `v2` APIs (see: `curl -X GET "https://orgbook.gov.bc.ca/api/v2/schema" -H  "accept: application/json"`).

The reason for this is likely the relatively recent move to `aries-vcr` and aca-py based agents, and the fact we re-published schemas for the new instance (@WadeBarnes can confirm), so this issue appears to still be actual.

**Comment by WadeBarnes** [comment] 2020-12-16 20:28
Confirmed, the API is returning all of the registered schemas.  Due to the recent moves and reloads we only have the one version of each of the schemas.

```
OrgBook=# select * from schema;
 id |       create_timestamp        |       update_timestamp        |                name                | version |       origin_did       
----+-------------------------------+-------------------------------+------------------------------------+---------+------------------------
  4 | 2020-08-19 21:20:43.840861+00 | 2020-09-09 19:12:26.486246+00 | cannabis-retail-store-licence.lcrb | 1.0.23  | JNXZGR4Kfyakzi7Wu4Qics
  5 | 2020-08-19 21:20:43.901605+00 | 2020-09-09 19:12:26.518147+00 | cannabis-marketing-licence.lcrb    | 1.0.8   | JNXZGR4Kfyakzi7Wu4Qics
  1 | 2020-02-14 22:27:35.665876+00 | 2020-12-02 21:00:36.822941+00 | registration.registries.ca         | 1.0.42  | HR6vs6GEZ8rHaVgjg2WodM
  2 | 2020-02-14 22:27:35.716133+00 | 2020-12-02 21:00:36.846008+00 | relationship.registries.ca         | 1.0.42  | HR6vs6GEZ8rHaVgjg2WodM
  3 | 2020-02-14 22:27:35.734619+00 | 2020-12-02 21:00:36.860146+00 | address.registries.ca              | 1.0.42  | HR6vs6GEZ8rHaVgjg2WodM
  7 | 2020-09-18 20:55:52.739985+00 | 2020-12-02 21:00:36.872083+00 | business_number.registries.ca      | 1.0.42  | HR6vs6GEZ8rHaVgjg2WodM
  ```

**Closed** 2021-05-20 16:50 UTC
